import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const app = readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8');
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const css = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const dateArrow = readFileSync(new URL('../public/assets/icon-date-arrow.svg', import.meta.url), 'utf8');
const manifest = JSON.parse(readFileSync(new URL('../public/site.webmanifest', import.meta.url), 'utf8'));
const schema = readFileSync(new URL('../supabase/schema.sql', import.meta.url), 'utf8');
const serviceWorker = readFileSync(new URL('../public/sw.js', import.meta.url), 'utf8');
const webPushFunction = readFileSync(new URL('../supabase/functions/send-web-push/index.ts', import.meta.url), 'utf8');

function getEntryDateTimeForTest(entry) {
  const labelMatch = String(entry.dateLabel || '').match(/(\d{1,2})월\s*(\d{1,2})일/);
  if (labelMatch) {
    const weekYearMatch = String(entry.weekId || '').match(/week-(\d{4})-/);
    const year = weekYearMatch ? Number(weekYearMatch[1]) : 2026;
    return new Date(year, Number(labelMatch[1]) - 1, Number(labelMatch[2])).getTime();
  }

  const date = new Date(`${entry.date}T00:00:00`);
  return Number.isNaN(date.getTime()) ? 0 : date.getTime();
}

function sortEntriesByDateAscendingForTest(entries) {
  return entries.slice().sort((a, b) => getEntryDateTimeForTest(a) - getEntryDateTimeForTest(b));
}

const visibleDateOrder = sortEntriesByDateAscendingForTest([
  { id: 'late', weekId: 'week-2026-05-22', date: '2026-05-22', dateLabel: '5월 28일' },
  { id: 'early', weekId: 'week-2026-05-22', date: '2026-05-28', dateLabel: '5월 25일' },
]).map((entry) => entry.id).join(',');

const commentOrder = [
  { id: 'new', createdAt: '2026-07-04T15:00:00.000Z' },
  { id: 'old', createdAt: '2026-07-04T14:00:00.000Z' },
].slice().sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()).map((comment) => comment.id).join(',');

const checks = [
  ['index loads app root', html.includes('id="app"')],
  ['app logo is exposed for browser bookmarks and saved links', html.includes('rel="icon"') && html.includes('href="%BASE_URL%app-icon-192-v20260703.png"') && html.includes('rel="apple-touch-icon"') && html.includes('sizes="180x180"') && html.includes('href="%BASE_URL%apple-touch-icon-v20260703.png"') && html.includes('rel="manifest"') && html.includes('href="%BASE_URL%site.webmanifest?v=20260703"') && manifest.name === '아보카도' && manifest.short_name === '아보카도' && manifest.start_url === '/avocadoo/' && manifest.icons.some((icon) => icon.src === 'app-icon-192-v20260703.png' && icon.sizes === '192x192') && manifest.icons.some((icon) => icon.src === 'app-icon-512-v20260703.png' && icon.sizes === '512x512')],
  ['figma splash covers initial server load for two seconds', app.includes("logo: './app-logo.png'") && app.includes('const splashMinimumDurationMs = 2000') && app.includes('function SplashScreen()') && app.includes('className="splash-screen"') && app.includes('className="splash-logo"') && app.includes('exit={{ opacity: 0 }}') && app.includes('duration: 0.25') && app.includes('ease: [0, 0, 0.58, 1]') && app.includes('const [isSplashMinimumElapsed, setIsSplashMinimumElapsed] = useState(false)') && app.includes('const [isInitialDataLoaded, setIsInitialDataLoaded] = useState(false)') && app.includes('const showSplash = !isSplashMinimumElapsed || !isInitialDataLoaded') && app.includes('setIsInitialDataLoaded(true)') && app.includes('window.setTimeout') && app.includes('splashMinimumDurationMs') && css.includes('.splash-screen') && css.includes('background: #ffffff') && css.includes('z-index: 300') && css.includes('.splash-logo') && css.includes('left: calc(50% - 85px)') && css.includes('top: calc(50% - 147px)') && css.includes('width: 170px') && css.includes('height: 170px')],
  ['framer motion dependency installed', Boolean(pkg.dependencies?.['framer-motion'])],
  ['upload buttons use framer motion', app.includes("from 'framer-motion'") && app.includes('motion.button') && !app.includes('layoutId="upload-button"')],
  ['home to list uses viewport-width 480 50 push spring', app.includes('const screenPushTransition') && app.includes('const defaultScreenPushDistance = 390') && app.includes('window.visualViewport?.width || window.innerWidth') && app.includes('const screenPushDistance = useViewportWidth()') && app.includes("currentScreen === 'home' && nextScreen === 'list'") && app.includes("'home-to-list'") && app.includes('stiffness: 480') && app.includes('damping: 50')],
  ['letter page component remains without a home entry point', !app.includes("currentScreen === 'home' && nextScreen === 'letter'") && !app.includes("'home-to-letter'") && app.includes("currentScreen === 'letter' && nextScreen === 'home'") && app.includes("'letter-to-home'") && app.includes('function LetterScreen') && app.includes('anniversaryLetterParagraphs') && app.includes('<img className="letter-page-name"') && !app.includes('onOpenLetter') && css.includes('.letter-screen') && css.includes('.letter-page-content') && css.includes('top: 60px') && css.includes('padding: 10px 24px 64px') && css.includes('.letter-page-body') && css.includes('line-height: 24px')],
  ['covered home moves half viewport width with 480 50 spring', app.includes('const coveredPageOffset = -screenPushDistance * 0.5') && app.includes('const coveredPageTransition') && app.includes('stiffness: 480') && app.includes('damping: 50') && app.includes("screenName === 'home') return { animate: { x: coveredPageOffset }, style: { zIndex: 1 }, transition: coveredPageTransition }")],
  ['list overlays home during push', app.includes('initial: { x: screenPushDistance, boxShadow: coveringPageShadow }') && app.includes('animate: { x: 0, boxShadow: restingPageShadow }') && app.includes('style: { zIndex: 2 }')],
  ['push layer depth uses temporary shadow and covered-page dim', app.includes("const coveringPageShadow = '-8px 0 14px rgba(31, 38, 48, 0.08)'") && app.includes("const restingPageShadow = 'none'") && app.includes('boxShadow: { duration: 0.14') && app.includes('function CoveredPageDim') && app.includes("<CoveredPageDim visible={transitionKind === 'home-to-list'} />") && app.includes("<CoveredPageDim visible={transitionKind === 'list-to-comment'} />") && css.includes('.page-dim') && css.includes('z-index: 40')],
  ['push screens share an absolute stage', app.includes('const showHome =') && app.includes('const showList =') && css.includes('.screen-stage') && css.includes('.screen-stage > .phone') && css.includes('position: absolute')],
  ['push transition screens unmount after animation', app.includes('const screenTransitionResetMs = 650') && app.includes('const screenTransitionResetTimer = useRef(null)') && app.includes('const screenTransitionRunId = useRef(0)') && app.includes("setScreenTransition('none')") && app.includes('window.clearTimeout(screenTransitionResetTimer.current)') && app.includes('screenTransitionRunId.current !== transitionRunId')],
  ['all pages support iOS-style edge swipe back', app.includes('function getBackScreen(screen, previousScreen)') && app.includes("if (screen === 'upload') return previousScreen === 'list' ? 'list' : 'home'") && app.includes('const screenRef = useRef(screen)') && app.includes('const shouldIgnoreNextPopState = useRef(false)') && app.includes('function getHomeHistoryState(kind = ') && app.includes("avocadooHomeHistory: kind") && app.includes("replaceHomeHistoryState('guard')") && app.includes('pushHomeHistoryState()') && app.includes('function applyNavigation(nextScreen, { pushHistory = true, animate = true } = {})') && app.includes("const nextTransition = animate ? getScreenTransition(nextScreen) : 'none'") && app.includes('setScreenTransition(nextTransition)') && app.includes("currentScreen === 'edit' && nextScreen === 'list'") && app.includes("window.history.go(previousScreen === 'comment' ? -2 : -1)") && app.includes("if (nextScreen === 'home' && typeof window !== 'undefined')") && app.includes("if (screenRef.current === 'home')") && app.includes("window.addEventListener('popstate', handlePopState)") && app.includes('navigateBack({ animate: false })') && !app.includes('const backSwipeGesture = useRef(null)') && !app.includes('onPointerDown={handleBackSwipePointerDown}')],
  ['home blocks native iOS edge back gesture only on home', app.includes('const homeEdgeBackSwipeBlocker = useRef({ active: false, startX: 0, startY: 0 })') && app.includes('function handleHomeEdgeTouchStart(event)') && app.includes("if (screenRef.current !== 'home' || event.touches.length !== 1)") && app.includes('const isLeftEdgeTouch = touch.clientX <= edgeWidth') && app.includes('if (isLeftEdgeTouch && event.cancelable)') && app.includes('event.preventDefault()') && app.includes('function handleHomeEdgeTouchMove(event)') && app.includes("if (!blocker.active || screenRef.current !== 'home' || event.touches.length !== 1) return") && app.includes('const isBackSwipeMotion = deltaX >= 0 && Math.abs(deltaX) >= Math.abs(deltaY)') && app.includes("window.addEventListener('touchstart', handleHomeEdgeTouchStart, { capture: true, passive: false })") && app.includes("window.addEventListener('touchmove', handleHomeEdgeTouchMove, { capture: true, passive: false })")],
  ['home month is synced to actual date', app.includes('const today = new Date()') && app.includes('const initialMonthStart = new Date(today.getFullYear(), today.getMonth(), 1)') && app.includes('function buildMonthWeeks(monthStart)') && app.includes('getMonthLastDay(monthStart)')],
  ['home month carousel spreads available months in one track', app.includes('function buildHomeMonthPages()') && app.includes('for (let offset = -24; offset <= 0; offset += 1)') && app.includes('const monthPages = useMemo(() => buildHomeMonthPages(), [])') && app.includes('className="home-month-track"') && css.includes('.home-month-page') && !css.includes('scroll-snap-type')],
  ['home month paging uses framer motion value instead of native scroll snap', app.includes("from 'framer-motion'") && app.includes('animate') && app.includes('motion') && app.includes('useMotionValue') && app.includes('const monthGesture = useRef(null)') && app.includes('const monthTrackX = useMotionValue(-activeMonthIndex * screenPushDistance)') && app.includes('function startMonthGesture(pointerId, x, y, source = ') && app.includes('function finishMonthGesture(pointerId, x, y, cancelled = false)') && !app.includes('drag="x"') && !app.includes('useAnimationControls') && !app.includes("viewport.addEventListener('touchmove'")],
  ['home mobile scroll axes keep vertical scroll while custom swipe handles horizontal', css.includes('touch-action: pan-y') && css.includes('overflow-x: hidden') && css.includes('overflow-y: hidden') && css.includes('.week-list') && css.includes('overflow-y: auto')],
  ['home month carousel pages from release swipe direction', app.includes('const deltaX = x - gesture.startX') && app.includes('const isHorizontalSwipe = absX > absY * 1.25') && app.includes('const isDistanceSwipe = absX >= getMonthSwipeThreshold(viewport)') && app.includes('const isFastSwipe = absX >= 24 && swipeVelocity >= getMonthSwipeVelocityThreshold()') && app.includes('const isValidSwipe = isHorizontalSwipe && (isDistanceSwipe || isFastSwipe)') && app.includes('moveToMonth(activeMonthIndex + (deltaX < 0 ? 1 : -1), viewport)') && app.includes('onChangeMonth(nextMonthDate)')],
  ['home month carousel animates active index with framer spring', app.includes('const targetTrackX = -clampedIndex * getMonthPageWidth(viewport)') && app.includes('animateMonthTrack(targetTrackX)') && app.includes('...screenPushTransition') && app.includes('style={{ x: monthTrackX }}')],
  ['home month carousel defers adjacent month render until slide completes', app.includes('function commitMonthChange(nextMonthIndex)') && app.includes('const canDeferMonthCommit = animated && Math.abs(clampedIndex - activeMonthIndex) === 1') && app.includes('animateMonthTrack(targetTrackX, () => commitMonthChange(clampedIndex))') && app.includes('commitMonthChange(clampedIndex);\n      animateMonthTrack(targetTrackX);')],
  ['home month header and page share the same active index state', app.includes('const [activeMonthIndex, setActiveMonthIndex]') && app.includes('const activeMonthDate = monthPages[activeMonthIndex]?.date || monthDate') && app.includes('const activeWeeks = monthWeeksByKey.get(getMonthKey(activeMonthDate)) || []') && app.includes('monthDate={activeMonthDate}') && app.includes('weeks={monthWeeksByKey.get(month.key) || []}')],
  ['home month carousel renders only nearby heavy month content', app.includes('function getHomeRenderableMonthIndexes(activeMonthIndex, monthCount)') && app.includes('const renderableMonthIndexes = useMemo(() => getHomeRenderableMonthIndexes(activeMonthIndex, monthPages.length), [activeMonthIndex, monthPages.length])') && app.includes('renderableMonthIndexes.forEach((index) => {') && app.includes('isRenderable={renderableMonthIndexes.has(index)}') && app.includes('aria-hidden={!isRenderable}') && app.includes('setMonthTrackPositionOnFrame(nextTrackX)') && app.includes('window.requestAnimationFrame(flushScheduledMonthTrackPosition)') && css.includes('will-change: transform') && css.includes('contain: layout paint style')],
  ['home month carousel does not recenter after paging', !app.includes('const targetTrackX = direction < 0 ? 0 : -monthPageWidth * 2') && !app.includes('monthTrackX.set(-getMonthPageWidth(nextViewport))') && !app.includes('key={getMonthKey(visibleMonthDate)}')],
  ['home month carousel resyncs to device width', app.includes('function getMonthPageWidth(viewport)') && app.includes('viewport?.clientWidth || screenPushDistance') && app.includes('resetMonthTrack(viewport)') && app.includes('}, [screenPushDistance]);') && css.includes('width: max-content')],
  ['home month carousel blocks future month scroll', app.includes('function buildHomeMonthPages()') && app.includes('offset <= 0') && app.includes('Math.min(Math.max(nextMonthIndex, 0), monthPages.length - 1)') && app.includes('snapMonthBack(viewport)')],
  ['home month gesture clears stale click blocking before week tap', app.includes('dragBlockedClick.current = false;\n    monthGesture.current = {') && app.includes('if (cancelled) {\n      if (gesture.isHorizontal) snapMonthBack(viewport);\n      dragBlockedClick.current = false;') && app.includes('if (!gesture.isHorizontal) {\n      dragBlockedClick.current = false;') && app.includes("function handleSelectWeek(week, nextScreen = 'list', source = '')")],
  ['home month header stays outside carousel track', app.includes('function HomeHeader({ monthDate, minMonth, maxMonth, onSelectMonth, onOpenNicknamePicker, currentNickname = currentMemberNickname })') && app.includes('monthDate={activeMonthDate}') && !app.includes('function HomeMonthPage({ monthDate') && css.includes('.home-header') && css.includes('z-index: 5')],
  ['home month selector opens native month picker and moves to selected month', app.includes('const monthInputRef = useRef(null)') && app.includes("typeof input.showPicker === 'function'") && app.includes('input.showPicker()') && app.includes('type="month"') && app.includes('value={getMonthKey(monthDate)}') && app.includes('min={minMonth}') && app.includes('max={maxMonth}') && app.includes('function handleSelectMonth(monthValue)') && app.includes('moveToMonth(nextMonthIndex, monthViewportRef.current)')],
  ['home month selector uses polaroid touch effect', app.includes('animate={{ scale: isPressed ? 0.98 : 1 }}') && app.includes('transition={isPressed ? polaroidPressSpring : polaroidReleaseSpring}') && app.includes('onPointerDown={() => setIsPressed(true)}') && css.includes('.month-picker-input') && css.includes('pointer-events: none')],
  ['home text dragging and selection is disabled', css.includes('.home-screen,\n.home-screen *') && css.includes('user-select: none') && css.includes('-webkit-user-select: none')],
  ['home month selector never wraps two digit months', css.includes('.month-select') && css.includes('width: max-content') && css.includes('min-width: 62px') && css.includes('white-space: nowrap') && css.includes('flex-wrap: nowrap')],
  ['home couple state matches figma 60 by 33 avatar badge', app.includes("avatarHemin: './assets/profile-hemin.svg'") && app.includes("avatarJeong: './assets/icon-avatar-jeong.svg'") && app.includes("avatarJeongNeutral: './assets/profile-jeong.svg'") && app.includes("heartBadge: './assets/icon-heart-badge.svg'") && app.includes("normalizeSelectedNickname(nickname) === '혜민민' ? assets.avatarHemin : assets.avatarJeongNeutral") && app.includes("normalizeSelectedNickname(currentNickname) === '정정욱' ? 'couple-avatar-selected' : ''") && app.includes("normalizeSelectedNickname(currentNickname) === '혜민민' ? 'couple-avatar-selected' : ''") && app.includes('src={assets.avatarHemin}') && app.includes('src={assets.avatarJeongNeutral}') && app.includes('src={assets.heartBadge}') && app.includes('currentNickname={currentNickname}') && css.includes('.couple-state') && css.includes('width: 60px') && css.includes('height: 33px') && css.includes('.couple-state > img:first-child') && css.includes('margin-right: -4px') && css.includes('.couple-state > img.couple-avatar-selected') && css.includes('outline: 2px solid #7acc2d') && css.includes('left: 50%') && css.includes('transform: translateX(-50%)') && css.includes('background: #7acc2d') && !css.includes('.nickname-option-selected img')],
  ['home couple state opens persisted nickname picker with touch effect', app.includes("const memberNicknames = ['혜민민', '정정욱']") && app.includes("const selectedNicknameStorageKey = 'avocadoo.member.nickname.v1'") && app.includes('function readSelectedNickname()') && app.includes('function writeSelectedNickname(nickname)') && app.includes('function NicknamePickerSheet') && app.includes('aria-label="닉네임 선택"') && app.includes('scale: isCouplePressed ? 0.94 : 1') && app.includes('onOpenNicknamePicker={() => setIsNicknamePickerOpen(true)}') && app.includes('className="nickname-picker-sheet"') && app.includes('initial={{ y: 292 }}') && app.includes('animate={{ y: 0 }}') && app.includes('exit={{ y: 292 }}') && app.includes('transition={screenPushTransition}') && app.includes('<AnimatePresence>') && app.includes('누구이신가요?') && app.includes('nickname-option-selected') && app.includes('onSelect(draftNickname)') && css.includes('.nickname-picker-sheet') && css.includes('height: 292px') && css.includes('border-radius: 24px 24px 0 0') && css.includes('.nickname-confirm-button') && css.includes('height: 57px')],
  ['home week list scrolls vertically only', css.includes('height: calc(100% - 63px)') && css.includes('overflow-x: hidden') && css.includes('overflow-y: auto') && css.includes('-webkit-overflow-scrolling: touch')],
  ['home week range font weight is semibold', css.includes('.week-copy strong') && css.includes('font-weight: 600')],
  ['home month pages own vertical scroll containers', app.includes('function HomeMonthPage({ weeks, onSelectWeek, isRenderable = true })') && app.includes('className="home-month-viewport"') && app.includes('onPointerMove={handleMonthPointerMove}') && app.includes('className="home-month-track"') && app.includes('<div className="week-list">')],
  ['home letter entry is removed', !app.includes('let homeLetterEntryWasRead') && !app.includes('readHomeLetterEntrySeen') && !app.includes('writeHomeLetterEntrySeen') && !app.includes('function HomeLetterEntry') && !app.includes('showLetterEntry') && !app.includes('homeEntrySpring') && !app.includes('homeEntryVariants') && !app.includes('floatingHomeEntryVariants') && !app.includes('entranceOrder=') && !css.includes('.home-letter-entry') && !css.includes('.letter-entry-copy') && !css.includes('.letter-read-button')],
  ['upload button width and y spring is 480 50', app.includes('const uploadButtonSizeSpring') && app.includes('stiffness: 480') && app.includes('damping: 50')],
  ['upload button radius spring is 800 55', app.includes('stiffness: 800') && app.includes('damping: 55')],
  ['upload button springs start together', app.includes('...uploadButtonSizeSpring') && app.includes('borderRadius: uploadButtonRadiusSpring')],
  ['upload button animates real responsive width not scale layout', app.includes('width: uploadButtonSize.small') && app.includes('const primaryUploadWidth = Math.max(uploadButtonSize.small, screenPushDistance - 32)') && app.includes('width: primaryUploadWidth') && !app.includes('LayoutGroup')],
  ['upload button press scales with separate springs', app.includes('const uploadButtonPressSpring') && app.includes('stiffness: 1000') && app.includes('const uploadButtonReleaseSpring') && app.includes('scale: isPressed ? 0.97 : 1') && app.includes('scale: isPressed ? uploadButtonPressSpring : uploadButtonReleaseSpring')],
  ['primary upload button press scales with separate springs', app.includes('scale: isUploadPressed ? 0.97 : 1') && app.includes('scale: isUploadPressed ? uploadButtonPressSpring : uploadButtonReleaseSpring') && app.includes('onPointerDown={() => setIsUploadPressed(true)}')],
  ['upload back animates responsive big to small', app.includes('reverseFromBig') && app.includes("previousScreen === 'upload'") && app.includes('bigWidth={Math.max(uploadButtonSize.small, screenPushDistance - 32)}') && app.includes('initial={reverseFromBig ? { borderRadius: uploadButtonRadius.big, width: bigWidth, y: -9.5 } : false}')],
  ['upload button label changes only font size', app.includes('animate={{ fontSize: 16 }}') && app.includes('animate={{ fontSize: 17 }}')],
  ['upload button label weight is semibold', /\.upload-button-label\s*\{[^}]*font-weight:\s*600/.test(css) && /\.floating-upload\s*\{[^}]*font-weight:\s*600/.test(css)],
  ['upload button content group is centered', css.includes('justify-content: center') && css.includes('gap: 6px') && !app.includes('className="upload-button-measure"') && !css.includes('var(--upload-icon-offset')],
  ['upload button radius morphs visible values', app.includes('small: 23') && app.includes('big: 16') && app.includes('borderRadius: uploadButtonRadius.small') && app.includes('borderRadius: uploadButtonRadius.big')],
  ['figma upload button colors and responsive size preserved', app.includes('small: 101') && app.includes('const primaryUploadWidth = Math.max(uploadButtonSize.small, screenPushDistance - 32)') && css.includes('background: #7acc2d') && css.includes('.primary-upload') && css.includes('width: 100%') && !css.includes('max-width: 358px') && css.includes('height: 57px')],
  ['small upload button hugs text and stays centered', app.includes('className="floating-upload-anchor"') && css.includes('width: max-content') && css.includes('padding: 12px 18px') && css.includes('white-space: nowrap') && css.includes('transform: translateX(-50%)')],
  ['upload buttons stay on top', css.includes('.floating-upload-anchor') && css.includes('z-index: 100') && css.includes('.bottom-cta') && css.includes('z-index: 40')],
  ['home polaroid press uses transform-only compression', app.includes('pressed: -48') && app.includes('const pressedX = index * (polaroidGap.pressed - polaroidGap.rest)') && app.includes('animate={{ x: compact ? pressedX : 0 }}') && app.includes('style={{ marginRight: isLast ? 0 : polaroidGap.rest }}') && app.includes('transition={compact ? polaroidPressSpring : polaroidReleaseSpring}') && app.includes('animate: { scale: isPressed ? 0.98 : 1 }') && !app.includes('animate={{ marginRight') && css.includes('will-change: transform')],
  ['list polaroid tap toggles expanded mode without date label', app.includes('toggleEnabled = false, showDateLabel = false') && app.includes('focusEnabled || !toggleEnabled') && app.includes('<LargePolaroidStack photos={normalizedEntry.photos} dateLabel={normalizedEntry.dateLabel} defaultExpanded={normalizedEntry.photos.length > 4} toggleEnabled />') && app.includes('const [isExpanded, setIsExpanded] = useState(defaultExpanded)') && app.includes('const largePolaroidCollapsedWidth = 180') && app.includes('width: expanded ? expandedWidth : largePolaroidCollapsedWidth') && app.includes('left: index * (largePolaroidWidth + largePolaroidPressedGap)') && app.includes('top: 0') && app.includes('rotate: 0') && app.includes("{showDateLabel ? <span className=\"large-date\">")],
  ['list polaroid expand and gather uses 480 50 spring', app.includes('const largePolaroidSpring') && app.includes('stiffness: 480') && app.includes('damping: 50') && app.includes('width: largePolaroidSpring') && app.includes('...largePolaroidSpring')],
  ['list polaroid expanded state scrolls horizontally', app.includes("className={`large-stack-scroll ${expanded ? 'large-stack-scroll-expanded' : ''}`}") && css.includes('.large-stack-scroll-expanded') && css.includes('overflow-x: auto')],
  ['list polaroid expanded scroll uses full device width with edge padding and no visible scrollbar', css.includes('width: calc(100% + 56px)') && css.includes('margin: 24px -28px') && css.includes('padding: 0 28px') && css.includes('scrollbar-width: none') && css.includes('.large-stack-scroll::-webkit-scrollbar') && css.includes('display: none')],
  ['list card expanded polaroid preserves height and 24px edge padding', css.includes('.diary-item-list-card .large-stack-scroll-expanded') && css.includes('height: 200px') && css.includes('margin: 24px 0') && css.includes('padding: 0 24px') && css.includes('padding-left: 24px') && css.includes('padding-right: 24px')],
  ['list polaroid gather only uses 0.03 stagger', app.includes('const largePolaroidStaggerDelay = 0.03') && app.includes('delay: expanded ? 0 : (visible.length - 1 - index) * largePolaroidStaggerDelay')],
  ['comment detail polaroid is locked to expanded row', app.includes("function LargePolaroidStack({ photos = [], dateLabel = '', defaultExpanded = false, lockedExpanded = false, focusEnabled = false, toggleEnabled = false, showDateLabel = false })") && app.includes('const expanded = lockedExpanded || isExpanded') && app.includes('if (!lockedExpanded) setIsExpanded((current) => !current)') && app.includes('<LargePolaroidStack photos={normalizedEntry.photos} dateLabel={normalizedEntry.dateLabel} defaultExpanded lockedExpanded focusEnabled />') && css.includes('.comments-screen .diary-item-detail .large-stack-scroll') && css.includes('width: calc(100% + 48px)') && css.includes('overflow-x: auto') && css.includes('.comments-screen .diary-item-detail .large-stack')],
  ['comment screen follows figma spacing', css.includes('.comments-screen .diary-item-detail,\n.comments-screen .diary-item-detail:first-child') && css.includes('padding: 0 24px') && css.includes('.comments-screen .diary-item-detail .reaction-bar') && css.includes('padding: 4px 20px 12px') && css.includes('padding: 20px 24px') && css.includes('padding: 10px 16px max(32px, env(safe-area-inset-bottom))') && css.includes('.reply-composer-keyboard-open') && css.includes('padding: 8px 12px 0') && css.includes('font-size: 15px') && css.includes('border-bottom: 0.5px solid rgba(42, 48, 56, 0.1)')],
  ['comment reply editor uses non-input editor with send-key handling', app.includes('const replyEditorRef = useRef(null)') && app.includes('className="reply-editor"') && app.includes('contentEditable="plaintext-only"') && app.includes('suppressContentEditableWarning') && app.includes('data-placeholder="답글 달기..."') && app.includes('enterKeyHint="send"') && app.includes("typeof form?.requestSubmit === 'function'") && app.includes("form?.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }))") && css.includes('.reply-editor:empty::before') && !app.includes('<input\n            type="text"\n            value={reply}') && !css.includes('.reply-field input')],
  ['comment reply editor text is vertically centered', css.includes('.reply-editor') && css.includes('display: flex') && css.includes('align-items: center') && css.includes('height: 32px') && css.includes('line-height: 22px')],
  ['comment composer docks above visual viewport keyboard and outside scroll', app.includes('const [isReplyFocused, setIsReplyFocused] = useState(false)') && app.includes('const [isKeyboardOpen, setIsKeyboardOpen] = useState(false)') && app.includes('const [keyboardBottomOffset, setKeyboardBottomOffset] = useState(0)') && app.includes('const visualBottom = (viewport?.offsetTop || 0) + visualHeight') && app.includes('setKeyboardBottomOffset(bottomOffset)') && app.includes("'--reply-keyboard-bottom': `${keyboardBottomOffset}px`") && app.includes('comments-screen-keyboard-open') && app.includes("isReplyKeyboardDocked ? 'reply-composer reply-composer-keyboard-open' : 'reply-composer'") && css.includes('.comments-screen-keyboard-open .comment-thread') && css.includes('height: calc(100% - 59px - var(--reply-keyboard-bottom, 0px))') && css.includes('bottom: var(--reply-keyboard-bottom, 0px)') && app.includes('onFocus={() => setIsReplyFocused(true)}') && app.includes('onBlur={() => setIsReplyFocused(false)}')],
  ['polaroid shadows match figma 6-153', css.includes('.polaroid-add .polaroid-paper') && css.includes('box-shadow: -2px 3px 5px 1px rgba(0, 0, 0, 0.09)') && css.includes('.large-photo') && css.includes('box-shadow: -1px 0 2px 1px rgba(0, 0, 0, 0.09)') && !css.includes('box-shadow: -2px 3px 4px 0.5px rgba(0, 0, 0, 0.12)') && !css.includes('box-shadow: -3.267px 4.9px 8.167px 1.633px rgba(0, 0, 0, 0.09)')],
  ['no external icon package', !app.includes('lucide') && !html.includes('lucide')],
  ['status bar removed', !app.includes('statusBar') && !css.includes('status-bar')],
  ['home weeks with diary select their list', app.includes('const hasDiary = week.photos.length > 0') && app.includes('className="week-card week-card-clickable"') && app.includes('onClick={() => onSelectWeek(week)}')],
  ['home week subtitle summarizes meet locations and count', app.includes('const weekEntries = sortEntriesByDate(entries.filter((entry) => entry.weekId === week.id))') && app.includes("weekEntries.length === 0\n        ? '안 만난 주ㅠㅠ'") && app.includes("locations.join(',')") && app.includes("}에서 ${weekEntries.length}번 만남") && app.includes("locations.length > 0 ? locations.join(',') : '어딘가'")],
  ['empty week add polaroid opens upload with date picker focus', app.includes('<article') && app.includes('className="week-card"') && app.includes('className="week-add-polaroid"') && app.includes("onSelectWeek(week, 'upload', 'add-polaroid')") && app.includes('const [shouldOpenUploadDatePicker, setShouldOpenUploadDatePicker] = useState(false)') && app.includes("setShouldOpenUploadDatePicker(nextScreen === 'upload' && source === 'add-polaroid')") && app.includes('autoOpenDatePicker={shouldOpenUploadDatePicker}') && css.includes('.week-card-clickable')],
  ['future weeks are not rendered', app.includes('const todayStart = new Date(today.getFullYear(), today.getMonth(), today.getDate())') && app.includes('if (monthStart > todayStart) return []') && app.includes('if (startDate > todayStart) break') && app.includes('{activeWeeks[0] ? (')],
  ['empty week add is not nested button', app.includes('role="button"') && app.includes('tabIndex={0}') && !app.includes('className="week-add-polaroid"\n        type="button"')],
  ['polaroid has real layout box', css.includes('.polaroid {\n  display: block;')],
  ['upload initializes selected week date', app.includes('startDate:') && app.includes('endDate:') && app.includes('useState(initialDate)') && app.includes('initialDate={selectedWeek.startDate}')],
  ['selected week focuses monthly list first', app.includes('const targetEntry = monthEntries.find((entry) => entry.weekId === selectedWeek.id)') && app.includes("list.scrollTo({ top: target.offsetTop, behavior: 'auto' })") && app.includes("focusedWeekRef.current = selectedWeek.id")],
  ['list renders all selected month entries', app.includes('function getMonthKeyForDate(value)') && app.includes('const selectedMonthKey = getMonthKeyForDate(selectedWeek.startDate)') && app.includes('entries.filter((entry) => getMonthKeyForDate(entry.date) === selectedMonthKey)') && !app.includes('const weekEntries = sortEntriesByDateAscending(entries.filter((entry) => entry.weekId === selectedWeek.id))')],
  ['list header follows scroll anchored week', app.includes('const [visibleWeek, setVisibleWeek]') && app.includes('const headerWeek = visibleWeek || selectedWeek') && app.includes('const anchorTop = list.scrollTop + 24') && app.includes('const nextWeek = weeksById.get(anchoredEntry.weekId) || getWeekForEntry(anchoredEntry, entries)') && app.includes('setVisibleWeek((current) =>') && app.includes('title={headerWeek.range}') && app.includes('sub={headerWeek.label}')],
  ['list renders diary dates oldest first and comments oldest first', visibleDateOrder === 'early,late' && commentOrder === 'old,new' && app.includes('function getEntryDateTime(entry)') && app.indexOf("String(entry.dateLabel || '').match(/(\\d{1,2})월\\s*(\\d{1,2})일/)") < app.indexOf('const date = new Date(`${entry.date}T00:00:00`)') && app.includes('function sortEntriesByDateAscending(entries)') && app.includes('const dateDiff = getEntryDateTime(a) - getEntryDateTime(b)') && app.includes('return aCreatedAt - bCreatedAt') && app.includes('function sortCommentsByCreatedAt(comments)') && app.includes('return aCreatedAt - bCreatedAt') && app.includes(".order('created_at', { ascending: true })") && app.includes('const monthEntries = useMemo(') && app.includes('const comments = sortCommentsByCreatedAt(entry?.comments || [])')],
  ['all list diary entries use the standardized diary card component', app.includes('function normalizeDiaryEntry(entry)') && app.includes('function DiaryListCard({ entry, onToggleLike, onOpenComments, onEdit, itemRef })') && app.includes('className="diary-item diary-item-created diary-item-list-card"') && app.includes('return detail ? <DiaryDetailCard entry={entry}') && app.includes(': <DiaryListCard entry={entry}')],
  ['list diary body opens comments on tap', app.includes('function DiaryCardBody({ entry, onOpen })') && app.includes("role: 'button'") && app.includes('tabIndex: 0') && app.includes('onClick: () => onOpen(entry)') && app.includes('onKeyDown: (event) => {') && app.includes('<DiaryCardBody entry={normalizedEntry} onOpen={onOpenComments} />') && css.includes('.diary-body-clickable') && css.includes('touch-action: manipulation')],
  ['diary body preserves paragraph breaks', app.includes('function DiaryEntryText({ text })') && app.includes('.split(/\\n{2,}/)') && app.includes("paragraph.split('\\n')") && app.includes('<br />') && app.includes('<DiaryEntryText text={entry.text} />') && css.includes('.diary-entry-text') && css.includes('gap: 10px') && css.includes('overflow-wrap: anywhere')],
  ['edit entry flow follows figma edit guide', app.includes('function EditEntry({ entry, transitionKind, screenPushDistance, onNavigate, onUpdateEntry, onDeleteEntry })') && app.includes('function EditHeader({ onBack, onDelete })') && app.includes('삭제하기') && app.includes('function LeaveEditModal') && app.includes('수정사항이 저장되지 않아요.') && app.includes('async function updateEntry(entryId, changes)') && app.includes(".from('diary_entries')") && app.includes('.update({') && app.includes("currentScreen === 'list' && nextScreen === 'edit'") && app.includes("currentScreen === 'comment' && nextScreen === 'edit'")],
  ['edit screen follows updated figma 134-2532 spacing and modal shadow', app.includes('function StaticUploadField') && app.includes('<div className="upload-content edit-content" data-grid-rows={uploadGridRows}>') && css.includes('.edit-nav-header') && css.includes('height: 61px') && css.includes('.edit-nav-row') && css.includes('top: 0') && css.includes('.edit-content') && css.includes('top: 61px') && css.includes('.edit-content .entry-form') && css.includes('margin-top: 30px') && css.includes('.edit-modal-layer') && css.includes('overflow: visible') && css.includes('box-shadow: 0 0 15px rgba(0, 0, 0, 0.25)') && !css.includes('filter: drop-shadow(0 0 15px rgba(0, 0, 0, 0.25))') && css.includes('letter-spacing: 0.144px')],
  ['edit leave modal uses requested translate and opacity motion', app.includes('const editModalMotion') && app.includes('initial: { opacity: 0, y: 100 }') && app.includes('animate: { opacity: 1, y: 0 }') && app.includes("type: 'spring'") && app.includes('stiffness: 480') && app.includes('damping: 50') && app.includes('duration: 0.2') && app.includes('ease: [0, 0, 0.2, 1]') && app.includes('<motion.section className="edit-leave-modal"')],
  ['pencil edit button has 42dp ghost touch target', css.includes('.pencil') && css.includes('width: 42px') && css.includes('height: 42px') && css.includes('margin-top: -11px') && css.includes('.pencil img') && css.includes('width: 20px')],
  ['standard diary card normalizes entry display values', app.includes('dateLabel: entry.dateLabel || formatDateLabel(entry.date)') && app.includes('weekday: entry.weekday || formatWeekday(entry.date)') && app.includes('photos: entry.photos || []') && app.includes('comments: entry.comments || []') && app.includes("if (typeof photo === 'string') return assets.photos[photo] || photo")],
  ['upload entry belongs to selected week', app.includes('weekId: selectedWeek.id')],
  ['diary list is scrollable', css.includes('overflow-y: auto') && css.includes('height: calc(100% - 60px)') && css.includes('padding-bottom: 142px')],
  ['list diary card follows figma 62-207 spacing and divider', css.includes('.diary-item-list-card') && css.includes('padding: 16px 0 0') && css.includes('.diary-item-list-card::after') && css.includes('height: 0.5px') && css.includes('background: rgba(42, 48, 56, 0.1)') && css.includes('width: calc(100% - 48px)') && css.includes('margin: 24px 24px') && css.includes('padding: 4px 24px 12px')],
  ['list reaction bar follows figma 62-415 spacing', css.includes('.diary-item-list-card .reaction-bar') && css.includes('gap: 8px') && css.includes('height: 54px') && css.includes('padding: 4px 24px 12px') && css.includes('.reaction-button') && css.includes('min-width: 0') && css.includes('gap: 4px') && css.includes('font-size: 15px') && css.includes('font-weight: 500') && css.includes('line-height: 22px')],
  ['like buttons trigger instagram-style haptics when liked', app.includes('const instagramLikeHapticMs = 10') && app.includes('function triggerInstagramLikeHaptic()') && app.includes("typeof navigator.vibrate !== 'function'") && app.match(/if \(nextLiked\) {\n      triggerInstagramLikeHaptic\(\);\n    }/g)?.length >= 2],
  ['no horizontal scroll layout', css.includes('overflow-x: hidden') && css.includes('width: 100vw') && css.includes('width: 100%')],
  ['list previews show up to max six photos', app.includes('photos.slice(0, maxUploadPhotos)') && app.includes('const maxUploadPhotos = 6') && app.includes('defaultExpanded={normalizedEntry.photos.length > 4}')],
  ['diary data keeps max six photos outside previews', app.includes('photos: entry.photos || []') && app.includes('photos.slice(0, maxUploadPhotos)') && app.includes('return photos.slice(0, maxUploadPhotos).map((photo, index) => {')],
  ['upload accepts max six photos and hides add at capacity', app.includes('const maxUploadPhotos = 6') && app.includes('const canAddPhoto = photos.length < maxUploadPhotos') && app.includes('{canAddPhoto ? (') && app.includes('photos.slice(0, maxUploadPhotos)') && !app.includes('Math.max(0, 5 - photos.length)')],
  ['photo loading and storage upload are optimized', app.includes('async function compressPhotoForUpload(file)') && app.includes('function getOptimizedPhotoSrc(photo, transform)') && app.includes('getPublicUrl(storagePath, { transform })') && app.includes('function PhotoImage({ photo, transform, eager = false })') && app.includes('onError={() => {') && app.includes('width: 640') && app.includes('quality: 75') && app.includes('const uploadFile = await compressPhotoForUpload(photo.file)') && app.includes("cacheControl: '31536000'") && app.includes("loading={eager ? 'eager' : 'lazy'}") && app.includes('decoding="async"')],
  ['web push notification opens related diary deep link without app title copy', webPushFunction.includes("url.searchParams.set('entry', entryId)") && webPushFunction.includes('title: nickname') && webPushFunction.includes("body: '새로운 일기를 작성했어요.'") && webPushFunction.includes("body: '좋아요를 남겼어요.'") && webPushFunction.includes("body: '댓글을 달았어요.'") && !webPushFunction.includes("title: '아보카도'") && serviceWorker.includes("const title = data.title || '알림'") && serviceWorker.includes("entryId: data.entryId || ''") && serviceWorker.includes('targetClient.navigate(targetUrl)') && app.includes('function getDeepLinkedEntryId()') && app.includes("new URLSearchParams(window.location.search).get('entry')") && app.includes('function getWeekForEntry(entry, entries)') && app.includes('const consumedDeepLinkedEntryId = useRef(') && app.includes("applyNavigation('comment', { pushHistory: false, animate: false })")],
  ['upload screen starts empty', !app.includes("const row = ['couple'") && app.includes('<UploadGrid photos={photos} onFiles={handleFiles} onRemovePhoto={removePhoto} />')],
  ['upload photos can be deleted from figma delete buttons', app.includes('photoDelete:') && app.includes('function removePhoto(photoId)') && app.includes('onRemove={() => onRemovePhoto(photo.id)}') && css.includes('.polaroid-remove') && css.includes('width: 22px') && css.includes('.polaroid-remove-left') && css.includes('backdrop-filter: blur(6px)') && css.includes('-webkit-backdrop-filter: blur(6px)')],
  ['mobile zoom and missing supabase schema are handled', html.includes('maximum-scale=1.0') && html.includes('user-scalable=no') && app.includes('function isMissingSupabaseSchema(error)') && app.includes('if (!hasSupabaseConfig) return readLocalEntries()') && css.includes('.polaroid-add .polaroid-image::after') && css.includes('font-size: 16px')],
  ['mobile safe area and touch effects are controlled', html.includes('theme-color" content="#FAF9F7"') && html.includes('#FAF9F7') && css.includes('-webkit-tap-highlight-color: transparent') && css.includes('-webkit-touch-callout: none') && css.includes('touch-action: manipulation')],
  ['mobile add polaroid dashed border renders all sides', css.includes('repeating-linear-gradient(90deg') && css.includes('repeating-linear-gradient(180deg') && css.includes('left top / 1.5px 100% no-repeat') && css.includes('right top / 1.5px 100% no-repeat')],
  ['upload submit creates list entry', app.includes('onCreateEntry({') && app.includes("onNavigate('list')")],
  ['sample entries never send non uuid ids to supabase writes', app.includes('function isSupabaseUuid(value)') && app.includes('!isSupabaseUuid(entryId)') && app.includes('!isSupabaseUuid(commentId)') && !app.includes('if (isMissingSupabaseSchema(error)) return sortEntriesByDate(sampleEntries)')],
  ['diary fetch avoids supabase relationship cache joins', app.includes("select('id, author_id, diary_date, location_text, body_text, created_at')") && app.includes("supabase.from('diary_images').select('id, entry_id, image_url, storage_path, sort_order').in('entry_id', entryIds)") && app.includes("supabase.from('couple_members').select('id, nickname').in('id', memberIds)") && app.includes('const membersById = new Map') && !app.includes('couple_members:author_id')],
  ['edit image save only writes changed images', app.includes('async function saveChangedDiaryImages(entryId, currentPhotos, nextPhotos)') && app.includes("supabase.from('diary_images').delete().in('id', removedImageIds)") && app.includes("supabase.from('diary_images')") && app.includes('.insert(insertedImages)') && app.includes('savedPhotos = await saveChangedDiaryImages(entryId, entry.photos || [], nextPhotos);') && !app.includes(".upsert(imageRows, { onConflict: 'entry_id,sort_order' })")],
  ['edit text save ignores diary image rls failures', app.includes('function isDiaryImagesPolicyError(error)') && app.includes("message.includes('row-level security') && message.includes('diary_images')") && app.includes('if (!isDiaryImagesPolicyError(imageError)) throw imageError;')],
  ['diary delete persists to supabase before local removal', app.includes("supabase.from('diary_comments').select('id').eq('entry_id', entryId)") && app.includes("supabase.from('diary_comment_likes').delete().in('comment_id', commentIds)") && app.includes("supabase.from('diary_entry_likes').delete().eq('entry_id', entryId)") && app.includes("supabase.from('diary_images').delete().eq('entry_id', entryId)") && app.includes("supabase.from('diary_entries').delete().eq('id', entryId).select('id')") && app.includes('deletedRows.length === 0') && schema.includes('public delete diary comments')],
  ['upload save preserves content and selected author with and without supabase', app.includes('const savedEntry = buildLocalSavedEntry({ ...entry, nickname: selectedMemberNickname }, entryId);') && app.includes('author_id: selectedMemberId') && app.includes('setEntriesAndCache((current) => [savedEntry, ...current]);') && app.includes("select('id, diary_date, location_text, body_text, created_at')") && app.includes('async function saveDiaryImages(entryId, photos)') && app.includes("select('id, image_url, storage_path, sort_order')") && !app.includes("if (imagesError && !isMissingSupabaseSchema(imagesError)) throw imagesError")],
  ['diary fallback persists across app restarts', app.includes("const localEntriesStorageKey = 'avocadoo.diary.entries.v1'") && app.includes('function readLocalEntries()') && app.includes('function writeLocalEntries(entries)') && app.includes('function setEntriesAndCache(nextEntriesOrUpdater)') && app.includes('writeLocalEntries(sortedEntries)') && app.includes('src: createPhotoPreviewUrl(file)') && app.includes('revokePhotoPreviewUrls(photos)')],
  ['upload date picker is native and scoped to selected week', app.includes('const dateInputRef = useRef(null)') && app.includes('const didAutoOpenDatePicker = useRef(false)') && app.includes("typeof input.showPicker === 'function'") && app.includes('input.showPicker()') && app.includes('type="date"') && app.includes('min={selectedWeek.startDate}') && app.includes('max={selectedWeek.endDate || selectedWeek.startDate}')],
  ['date input uses figma arrow instead of native calendar icon', dateArrow.includes('viewBox="0 0 24 24"') && dateArrow.includes('d="M9 6L15 12L9 18"') && css.includes('data:image/svg+xml') && css.includes("d='M9 6L15 12L9 18'") && css.includes('width: 128px') && css.includes('padding-right: 18px') && css.includes('/ 20px 20px no-repeat') && css.includes("stroke='%23C7C7C7'") && css.includes('.date-input::-webkit-calendar-picker-indicator') && css.includes('display: none')],
  ['upload form follows figma 3-236 grid and responsive form spacing', app.includes('const uploadGridColumnCount = 3') && app.includes('data-grid-rows={uploadGridRows}') && app.includes('data-rows={rowCount}') && css.includes('top: 96px') && css.includes('min-height: 123px') && css.includes('.upload-grid[data-rows="2"]') && css.includes('min-height: 259px') && css.includes('.upload-content[data-grid-rows="1"] .entry-form') && css.includes('clamp(28px, 4vh, 36px)') && css.includes('justify-content: center') && css.includes('margin-top: 41px') && css.includes('padding: 0 24px') && css.includes('color: #2a3038') && css.includes('font-weight: 500')],
  ['upload memo field has no mobile left inset', css.includes('.entry-form') && css.includes('margin-left: 0') && css.includes('.memo-field') && css.includes('padding: 20px 0 0') && css.includes('.memo-field textarea') && css.includes('padding: 0')],
  ['upload fields enter with staggered spring motion', app.includes('const uploadFieldSpring') && app.includes('stiffness: 480') && app.includes('damping: 50') && app.includes('delay: order * 0.03') && app.includes('hidden: { opacity: 0, y: 500 }') && app.includes('function AnimatedUploadField')],
  ['upload entry targets are animated individually', app.includes('<motion.div className="upload-content" data-grid-rows={uploadGridRows} variants={uploadContentVariants} initial="hidden" animate="visible">') && app.includes('<AnimatedUploadField order={0}>') && app.includes('<AnimatedUploadField order={3}>') && css.includes('.entry-form > div')],
  ['phone stage follows device viewport', css.includes('width: 100vw') && css.includes('height: 100dvh') && css.includes('flex: 0 0 100vw')],
  ['figma cta height and responsive width preserved', css.includes('.bottom-cta') && css.includes('padding: 24px 16px 32px') && css.includes('.primary-upload') && css.includes('width: 100%') && css.includes('height: 57px')],
];

const failed = checks.filter(([, pass]) => !pass);

if (failed.length) {
  console.error(failed.map(([name]) => `FAIL ${name}`).join('\n'));
  process.exit(1);
}

console.log(checks.map(([name]) => `PASS ${name}`).join('\n'));
