export const stickerMotionConfig = {
  gridColumns: 16,
  gridRows: 16,
  detachDistance: 86,
  detachTriggerDistance: 12,
  visualPeelDistance: 18,
  peelFeather: 0.16,
  curlAmount: 6,
  curlWidth: 0.1,
  floatingTipCurlAmount: 3.5,
  floatingTipCurlWidth: 0.09,
  perspectiveAmount: 0.006,
  liftOffset: 7,
  followDamping: 0.24,
  reducedCurlAmount: 3,
  reducedPeelMultiplier: 0.22,
  pointerLiftOffset: 8,
  dropDuration: 380,
  cancelDuration: 340,
  shadowOffsetMin: 2,
  shadowOffsetMax: 6,
  shadowAlphaMin: 0.02,
  shadowAlphaMax: 0.16,
  shadow: {
    resting: 'none',
  },
};
